#!/usr/bin/env bash
# Postgres in Docker; agents + Next on host. Or use: docker compose up --build
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
mkdir -p "$ROOT/logs"

# Vertex Agent Engine chat: set ORCHESTRATOR_AGENT_ENGINE_RESOURCE in config/gcp.env (gitignored).
if [[ -f "$ROOT/config/gcp.env" ]]; then
  set -a
  # shellcheck source=/dev/null
  source "$ROOT/config/gcp.env"
  set +a
  echo ">>> Loaded config/gcp.env (GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT:-})"
fi

PYTHON_BIN="$ROOT/.venv/bin/python"
if [[ ! -x "$PYTHON_BIN" ]]; then
  echo ">>> Creating .venv..."
  python3 -m venv "$ROOT/.venv"
  "$ROOT/.venv/bin/pip" install -q -r "$ROOT/agents/cost_agent/requirements.txt" -r "$ROOT/agents/orchestrator/requirements.txt"
  PYTHON_BIN="$ROOT/.venv/bin/python"
fi

SPEECH_SA="$ROOT/frontend/.secrets/speech-sa.json"
if [[ -f "$SPEECH_SA" ]]; then
  if [[ -z "${GOOGLE_APPLICATION_CREDENTIALS:-}" ]]; then
    export GOOGLE_APPLICATION_CREDENTIALS="$SPEECH_SA"
  fi
  if [[ -z "${GOOGLE_CLOUD_PROJECT:-}" ]]; then
    GOOGLE_CLOUD_PROJECT="$("$PYTHON_BIN" -c "import json, pathlib; print(json.loads(pathlib.Path('$SPEECH_SA').read_text(encoding='utf-8'))['project_id'])")"
    export GOOGLE_CLOUD_PROJECT
  fi
fi

echo ">>> Starting postgres..."
if docker compose version >/dev/null 2>&1; then
  DC=(docker compose)
else
  DC=(docker-compose)
fi
"${DC[@]}" up -d postgres

for i in $(seq 1 90); do
  if "${DC[@]}" exec -T postgres pg_isready -U postgres >/dev/null 2>&1; then
    break
  fi
  sleep 1
done

if ! "${DC[@]}" exec -T postgres psql -U postgres -d postgres -tAc "SELECT to_regclass('public.cloud_costs');" | grep -q cloud_costs; then
  echo ">>> Applying database/schema.sql..."
  "${DC[@]}" exec -T postgres psql -U postgres -d postgres < "$ROOT/database/schema.sql"
fi

if ! "${DC[@]}" exec -T postgres psql -U postgres -d postgres -tAc "SELECT to_regclass('public.chat_sessions');" | grep -q chat_sessions; then
  echo ">>> Applying database/schema_chat_memory.sql..."
  "${DC[@]}" exec -T postgres psql -U postgres -d postgres < "$ROOT/database/schema_chat_memory.sql"
fi

if ! "${DC[@]}" exec -T postgres psql -U postgres -d postgres -tAc "SELECT to_regclass('public.chat_session_summaries');" | grep -q chat_session_summaries; then
  echo ">>> Applying database/schema_chat_memory_migration_002.sql..."
  "${DC[@]}" exec -T postgres psql -U postgres -d postgres < "$ROOT/database/schema_chat_memory_migration_002.sql"
fi

# Host stack must use docker compose Postgres (published :5435; 5433 is often another local Postgres).
# config/gcp.env may set DATABASE_URL for other targets — start-all forces local compose. Override with START_ALL_DATABASE_URL if needed.
export DATABASE_URL="${START_ALL_DATABASE_URL:-postgresql://postgres:postgres@127.0.0.1:5435/postgres}"
# Orchestrator requires DATABASE_URL for chat persistence. Dev default: accept requests without JWT.
export ORCHESTRATOR_AUTH_DISABLED="${ORCHESTRATOR_AUTH_DISABLED:-1}"
export COST_AGENT_CARD_URL="${COST_AGENT_CARD_URL:-http://127.0.0.1:8001/.well-known/agent.json}"
export COST_AGENT_TASKS_URL="${COST_AGENT_TASKS_URL:-http://127.0.0.1:8001/tasks/send}"

# BigQuery Cloud Billing export (cost agent). Override in config/gcp.env.
export BQ_BILLING_PROJECT="${BQ_BILLING_PROJECT:-${GOOGLE_CLOUD_PROJECT:-}}"
export BQ_BILLING_DATASET="${BQ_BILLING_DATASET:-gcp_billing_data}"
export BQ_BILLING_TABLE="${BQ_BILLING_TABLE:-gcp_billing_export_resource_v1_01B40E_943432_338729}"

echo ">>> Starting cost-agent :8001..."
(cd "$ROOT/agents/cost_agent" && nohup "$PYTHON_BIN" -m uvicorn main:app --host 127.0.0.1 --port 8001 \
  >"$ROOT/logs/cost-agent.log" 2>"$ROOT/logs/cost-agent.err.log" &)
sleep 2

echo ">>> Starting orchestrator :8000..."
(cd "$ROOT/agents/orchestrator" && nohup "$PYTHON_BIN" -m uvicorn main:app --host 127.0.0.1 --port 8000 \
  >"$ROOT/logs/orchestrator.log" 2>"$ROOT/logs/orchestrator.err.log" &)
sleep 2

if [[ ! -d "$ROOT/frontend/node_modules" ]]; then
  echo ">>> npm ci..."
  (cd "$ROOT/frontend" && npm ci)
fi

# Next.js loads .env.development.local over .env.local — no manual .env edits for local UI.
FRONTENV="$ROOT/frontend/.env.development.local"
{
  echo "# Generated by scripts/start-all.sh — do not edit (recreated on each start)"
  echo "NEXT_PUBLIC_ORCHESTRATOR_URL=http://127.0.0.1:8000"
  echo "NEXT_PUBLIC_USE_CHAT_PROXY=1"
  echo "ORCHESTRATOR_SERVER_URL=http://127.0.0.1:8000"
  if [[ -f "$SPEECH_SA" ]]; then
    echo "GOOGLE_APPLICATION_CREDENTIALS=$SPEECH_SA"
  fi
  if [[ -n "${GOOGLE_CLOUD_PROJECT:-}" ]]; then
    echo "GOOGLE_CLOUD_PROJECT=$GOOGLE_CLOUD_PROJECT"
  fi
} >"$FRONTENV"
echo ">>> Wrote $FRONTENV (local UI env; no manual copy from .env.example)"

echo ">>> Starting frontend :3000..."
(cd "$ROOT/frontend" && nohup npm run dev -- --hostname 127.0.0.1 --port 3000 \
  >"$ROOT/logs/frontend.log" 2>"$ROOT/logs/frontend.err.log" &)

echo ""
echo "Done. Open http://127.0.0.1:3000"
if [[ "$(uname -s)" == "Darwin" ]]; then
  sleep 1
  open "http://127.0.0.1:3000" 2>/dev/null || true
fi
echo "Logs: $ROOT/logs/"
echo "Stop: pkill -f 'uvicorn main:app' ; pkill -f 'next dev'  (careful on shared machines)"
